// src/aiact.js — 8ª categoria INFORMATIVA: "Trasparenza AI Act".
// Rileva dall'HTML servito i segnali che l'AI Act rende rilevanti dal 2 agosto 2026:
// sistemi conversazionali (art. 50 §1), pratiche vietate (art. 5), marcatura dei
// contenuti sintetici (art. 50 §2/§4), informativa IA, segnali di mercato UE (art. 2).
//
// LIMITI DICHIARATI, non finti:
// - Lo scan vede il markup, non il ruolo giuridico: provider vs deployer, classe di
//   rischio e casi d'uso NON sono deducibili da una pagina → li chiede `aiactAssess.js`.
// - NON pesa sullo score GEO (informational: true), come analyzeRights/analyzeTech.
// - NON dichiara conformità. Mai. Vedi il precedente in src/statement.js.
//
// Riferimenti: Reg. (UE) 2024/1689 art. 2 (ambito), 4 (alfabetizzazione), 5 (pratiche
// vietate), 50 (trasparenza), 99 (sanzioni). Applicabilità: art. 113 + Digital Omnibus.

import { fetchText, has, normUrl } from './lib.js';
import { makeT } from './messages/index.js';

const clamp = (n) => Math.max(0, Math.min(100, Math.round(n)));
const pct = (a, b) => (b ? (a / b) * 100 : 0);

// ── Cataloghi di rilevamento ────────────────────────────────────────────────
// Vendor conversazionali diffusi + plugin WP. Un match = "c'è un'interfaccia che
// parla con l'utente", non "è IA generativa": l'art. 50 §1 copre comunque
// l'interazione uomo-macchina, quindi il dovere di dichiararlo non cambia.
const CHAT_VENDORS = [
  ['Intercom', /widget\.intercom\.io|intercomcdn|window\.Intercom/i],
  ['Drift', /js\.driftt\.com|drift\.com\/include/i],
  ['Tidio', /code\.tidio\.co|tidiochat/i],
  ['Crisp', /client\.crisp\.chat|\$crisp/i],
  ['Zendesk / Sunshine', /static\.zdassets\.com|zopim|zE\(/],
  ['LiveChat', /cdn\.livechatinc\.com|__lc\b/i],
  ['HubSpot Conversations', /js\.hs-scripts\.com|hubspotconversations/i],
  ['Tawk.to', /embed\.tawk\.to/i],
  ['Freshchat', /wchat\.freshchat\.com|fcWidget/i],
  ['Smartsupp', /smartsuppchat|smartsupp\.com/i],
  ['Botpress', /cdn\.botpress\.cloud|botpressWebChat/i],
  ['Landbot', /cdn\.landbot\.io|landbot\.pro/i],
  ['Voiceflow', /cdn\.voiceflow\.com/i],
  ['Chatbase', /chatbase\.co\/embed|chatbase\.co\/chatbot-iframe/i],
  ['ManyChat', /mccdn\.me|manychat\.com/i],
  ['Google Dialogflow', /<df-messenger|dialogflow-console|df-messenger\.js/i],
  ['Typebot', /typebot\.io\/(?:embed|bundle)/i],
  ['Kommunicate', /kommunicate\.io\/v\d/i],
  // Plugin WP: solo token propri del plugin. `ai-engine` da solo pescava il link
  // marketing "fin.ai/ai-engine" di Intercom e lo etichettava come plugin WordPress.
  ['AI Engine (WP)', /mwai-chatbot|mwai_chatbot|mwai-form|plugins\/ai-engine\//i],
  ['WPBot (WP)', /qcld-wpbot|wpbot-?(?:chat|widget)/i],
  // Endpoint reali, non la semplice menzione del dominio in una pagina di documentazione.
  ['OpenAI diretto', /api\.openai\.com\/v1/i],
  ['Anthropic diretto', /api\.anthropic\.com\/v1/i],
  // Fallback generico: attributi/classi esplicite. Ultimo, così i vendor noti vincono.
  ['widget generico', /(?:id|class|data-[\w-]+)=["'][^"']*(?:chat-?bot|ai-?assistant|chat-?widget)/i],
];

// Riconoscimento emozioni e biometria: art. 5 (vietato su lavoro/istruzione) e
// categoria ad alto rischio altrove. Un match qui è un allarme, non una nota.
const EMOTION_VENDORS = [
  ['face-api.js', /face-api(?:\.min)?\.js/i],
  ['MorphCast', /morphcast|mphdxsdk/i],
  ['Affectiva', /affectiva|affdex/i],
  ['Hume AI', /api\.hume\.ai/i],
  ['FaceIO', /cdn\.faceio\.net/i],
  ['MediaPipe Face', /mediapipe.*face|face_mesh/i],
  ['Clarifai', /api\.clarifai\.com/i],
];

// Marcatori di provenienza dei contenuti sintetici (C2PA / IPTC / meta espliciti).
const PROVENANCE = [
  ['C2PA / Content Credentials', /c2pa|content-credentials|contentauthenticity/i],
  ['IPTC digitalSourceType', /digitalSourceType/i],
  ['meta ai-generated', /<meta[^>]+name=["'](?:ai-generated|ai-content|generator-ai)["']/i],
];

// Termini di disclosure in 6 lingue. Cerchiamo nel TESTO VISIBILE, non negli attributi:
// una classe "ai-chat" non è una comunicazione all'utente.
const DISCLOSURE_TERMS =
  /assistente virtuale|assistente automatico|chatbot|intelligenza artificiale|generato con (?:l')?(?:ia|ai)|risposta automatica|virtual assistant|ai assistant|automated assistant|ai-generated|generated by ai|ki-assistent|virtueller assistent|künstliche intelligenz|assistant virtuel|intelligence artificielle|asistente virtual|inteligencia artificial|assistente virtual|inteligência artificial/i;

// Link a un'informativa IA dedicata (distinta dalla privacy policy).
const AI_POLICY_LINK =
  /href=["'][^"']*(?:ai-policy|ai-notice|informativa-ia|informativa-ai|intelligenza-artificiale|ai-transparency|uso-dell-ia|ai-disclosure)/i;
const PRIVACY_LINK = /href=["'][^"']*(?:privacy|datenschutz|confidentialite|privacidad|privacidade)/i;

// Decisioni automatizzate: rilevante per art. 22 GDPR e art. 21 nLPD (Svizzera),
// che restano in vigore a prescindere dall'AI Act.
const AUTOMATED_DECISION =
  /decision[ei] automatizzat|profilazione|automated decision|automatisierte entscheidung|décision automatisée|decisión automatizada|decisão automatizada/i;

// Segnali che il servizio si rivolge (anche) al mercato UE → art. 2 §1 lett. c:
// l'AI Act si applica se l'OUTPUT è usato nell'Unione, non solo se sei stabilito lì.
// Euristica, non prova: serve a dire "verifica", non "sei dentro".
const EU_SIGNALS = [
  ['hreflang UE', /hreflang=["'](?:it|de|fr|es|pt|nl|pl|el|ro|cs|sv|da|fi|hu|bg|hr|sk|sl|et|lv|lt|ga|mt)(?:-[A-Z]{2})?["']/],
  ['prezzi in euro', /(?:€|EUR\b|\beuro\b)/i],
  // Solo dentro un URL: il vecchio `\.(?:it|de|pl|pt…)\b` pescava le classi CSS di
  // Tailwind (`.pl-1`, `.pt-0`) e dichiarava segnali UE su qualunque sito moderno.
  ['dominio o riferimento UE', /https?:\/\/[a-z0-9.-]+\.(?:eu|it|de|fr|es|pt|nl|be|at|ie|fi|se|dk|pl)(?=[:/?#"'\s]|$)/i],
  ['partita IVA / VAT UE', /\b(?:p\.?\s?iva|partita iva|vat\s?(?:id|number)?|ust-idnr|tva)\b/i],
  ['cookie banner GDPR', /gdpr|rgpd|dsgvo/i],
];

// Rimuove script/style/tag: cerchiamo la disclosure nel testo che l'utente legge.
function visibleText(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ');
}

function matchAll(catalog, html) {
  return catalog.filter(([, re]) => re.test(html)).map(([name]) => name);
}

// ── Rilevamento (funzione PURA, testabile senza rete) ───────────────────────
export function detectAiSignals(html, { url = '' } = {}) {
  const h = html || '';
  const text = visibleText(h);
  const hay = h + ' ' + url;
  return {
    chatbots: matchAll(CHAT_VENDORS, h),
    emotion: matchAll(EMOTION_VENDORS, h),
    provenance: matchAll(PROVENANCE, h),
    botDisclosure: DISCLOSURE_TERMS.test(text),
    aiPolicyLink: has(h, AI_POLICY_LINK),
    privacyLink: has(h, PRIVACY_LINK),
    automatedDecision: AUTOMATED_DECISION.test(text),
    euSignals: matchAll(EU_SIGNALS, hay),
  };
}

// ── Analisi (funzione PURA) ────────────────────────────────────────────────
export function analyzeAiAct(signals, lang = 'it') {
  const t = makeT(lang);
  const s = signals || {};
  const bots = s.chatbots || [];
  const emo = s.emotion || [];
  const prov = s.provenance || [];
  const eu = s.euSignals || [];

  const checks = [
    // art. 50 §1 — l'utente deve sapere che sta interagendo con una macchina.
    bots.length
      ? {
          name: t('aiact.chatbot.name'),
          status: s.botDisclosure ? 'good' : 'crit',
          detail: t(s.botDisclosure ? 'aiact.chatbot.detail.ok' : 'aiact.chatbot.detail.missing', {
            vendors: bots.join(', '),
          }),
          fix: s.botDisclosure ? null : t('aiact.chatbot.fix'),
          ref: 'art. 50 §1',
        }
      : {
          name: t('aiact.chatbot.name'),
          status: 'info',
          detail: t('aiact.chatbot.detail.none'),
          ref: 'art. 50 §1',
        },

    // art. 5 — riconoscimento emozioni/biometria: vietato o alto rischio.
    {
      name: t('aiact.emotion.name'),
      status: emo.length ? 'crit' : 'good',
      detail: emo.length
        ? t('aiact.emotion.detail.found', { vendors: emo.join(', ') })
        : t('aiact.emotion.detail.none'),
      fix: emo.length ? t('aiact.emotion.fix') : null,
      ref: 'art. 5',
    },

    // art. 50 §2/§4 — marcatura dei contenuti sintetici. Dall'HTML NON si sa se il
    // contenuto è generato: dichiariamo il limite invece di inventare un verdetto.
    {
      name: t('aiact.provenance.name'),
      status: 'info',
      detail: prov.length
        ? t('aiact.provenance.detail.found', { markers: prov.join(', ') })
        : t('aiact.provenance.detail.none'),
      fix: t('aiact.provenance.fix'),
      ref: 'art. 50 §2, §4',
    },

    // Informativa IA dedicata: non obbligatoria in sé, ma è il posto dove le
    // informazioni dell'art. 50 diventano verificabili da terzi.
    {
      name: t('aiact.notice.name'),
      status: s.aiPolicyLink ? 'good' : bots.length ? 'warn' : 'info',
      detail: t(s.aiPolicyLink ? 'aiact.notice.detail.ok' : 'aiact.notice.detail.none'),
      fix: s.aiPolicyLink ? null : t('aiact.notice.fix'),
      ref: 'art. 50',
    },

    // GDPR art. 22 / nLPD art. 21 — restano in vigore accanto all'AI Act.
    {
      name: t('aiact.decisions.name'),
      status: 'info',
      detail: t(s.automatedDecision ? 'aiact.decisions.detail.found' : 'aiact.decisions.detail.none'),
      ref: 'GDPR art. 22 · nLPD art. 21',
    },

    // art. 2 — ambito territoriale. Euristica: alimenta il questionario, non decide.
    {
      name: t('aiact.scope.name'),
      status: 'info',
      detail: eu.length
        ? t('aiact.scope.detail.eu', { signals: eu.join(', ') })
        : t('aiact.scope.detail.none'),
      fix: t('aiact.scope.fix'),
      ref: 'art. 2 §1',
    },
  ];

  const scored = checks.filter((c) => c.status !== 'info');
  const good = scored.filter((c) => c.status === 'good').length;
  // Con meno di due controlli valutabili il punteggio NON esiste: su un sito senza
  // chatbot restava solo "nessuna libreria di emozioni" e usciva un 100/100 che
  // sembrava una promozione a pieni voti. Meglio nessun numero che un numero falso.
  const score = scored.length < 2 ? null : clamp(pct(good, scored.length));
  return {
    informational: true,
    module: 'aiact',
    // Il punteggio misura i SEGNALI DI TRASPARENZA rilevabili, non la conformità.
    score,
    disclaimer: t('aiact.disclaimer'),
    signals: s,
    checks,
  };
}

export const AIACT_LABEL = 'Trasparenza AI Act';

// ── Orchestratore con rete (stesso contratto di auditA11y) ──────────────────
export async function auditAiAct(rawUrl, { lang = 'it' } = {}) {
  const url = normUrl(rawUrl);
  const page = await fetchText(url);
  const html = page.body || '';
  const signals = html ? detectAiSignals(html, { url }) : null;
  return {
    url,
    host: new URL(url).host,
    fetchedOk: page.ok,
    // Perché la scansione non è riuscita. Il nome NON è `error`: nel resto del
    // motore `x.error` significa «questo audit è fallito del tutto», e qui la
    // scansione è facoltativa — il questionario resta valido senza di essa.
    scanError: page.ok ? undefined : page.error,
    blocked: page.blocked || undefined,
    result: signals ? analyzeAiAct(signals, lang) : null,
  };
}
